#!/usr/local/bin/php

<?php
require __DIR__ . '/vendor/autoload.php';

use ASPTest\Adapter\Command\CreateNewUserCommand;
use ASPTest\Adapter\Command\CreateUserPasswordCommand;
use ASPTest\Domain\UseCase\CreateNewUser;
use ASPTest\Domain\UseCase\CreateUserPassword;
use DI\ContainerBuilder;
use Symfony\Component\Console\Application;

$containerBuilder = new ContainerBuilder();
$config = require __DIR__ . '/config.php';
$config($containerBuilder);

$settings = require __DIR__ . '/dependencies.php';
$settings($containerBuilder);

$repositories = require __DIR__ . '/repositories.php';
$repositories($containerBuilder);

$container = $containerBuilder->build();

$container->get(CreateNewUser::class);
$application = new Application();
$application->add(new CreateNewUserCommand(
    $container->get(CreateNewUser::class),
));
$application->add(new CreateUserPasswordCommand(
    $container->get(CreateUserPassword::class),
));
$application->run();