version: '3.8'
services:
  app:
    container_name: 'asp-test'
    build: ./
    image: php:7.3-cli
    working_dir: /usr/src/asp-test
    environment:
      docker: "true"
    volumes:
      - .:/usr/src/asp-test
    links:
      - db
    depends_on:
      - db

  db:
    container_name: 'asp-test-db'
    restart: on-failure
    image: mariadb
    env_file:
      - .env
    ports:
      - 3307:3307